#!/bin/bash
# set -eu

echo " -> Removing docker images"
docker rm -vf zabbix_server

echo " -> Rebuilding the image from current directory"
docker build -t klevo/zabbix_server .

echo " -> Ensure linked containers are running"
docker start mysql postfix_mandrill

echo " -> Run the new container"
docker run -d --name zabbix_server \
  --link mysql:mysql \
  --link postfix_mandrill:postfix_relay \
  -e ZABBIX_DB_NAME=zabbix \
  -e ZABBIX_DB_USER=root \
  -e ZABBIX_DB_PASSWORD=mypass \
  -e ZABBIX_AGENT_HOSTNAME=stream \
  -p 8081:80 \
  klevo/zabbix_server

echo " -> Done."
docker ps

docker exec -i -t zabbix_server /bin/bash
