#!/bin/bash

# Set up the config
sed -i "s/MYSQL_PORT_3306_TCP_ADDR/$MYSQL_PORT_3306_TCP_ADDR/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_NAME/$ZABBIX_DB_NAME/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_USER/$ZABBIX_DB_USER/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_PASSWORD/$ZABBIX_DB_PASSWORD/" /etc/zabbix/zabbix_server.conf

# Since zabbix_server can not (yet) run in the foreground, we need to hack around it:
# http://serverfault.com/questions/608069/managing-daemons-with-supervisor-no-foreground-mode-available
set -eu

pidfile="/var/run/zabbix/zabbix_server.pid"
command=/opt/zabbix/sbin/zabbix_server -c /etc/zabbix/zabbix_server.conf

# Proxy signals
function kill_app(){
    kill $(cat $pidfile)
    echo "zabbix_server killed"
    exit 0 # exit okay
}
trap "kill_app" SIGINT SIGTERM

# Launch daemon
$command
echo "zabbix_server started"
sleep 2

# Loop while the pidfile and the process exist
while [ -f $pidfile ] && kill -0 $(cat $pidfile) ; do
    sleep 1
done
