#!/bin/bash

# Set up the config
sed -i "s/MYSQL_PORT_3306_TCP_ADDR/$MYSQL_PORT_3306_TCP_ADDR/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_NAME/$ZABBIX_DB_NAME/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_USER/$ZABBIX_DB_USER/" /etc/zabbix/zabbix_server.conf
sed -i "s/ZABBIX_DB_PASSWORD/$ZABBIX_DB_PASSWORD/" /etc/zabbix/zabbix_server.conf

zabbix_server

# Just entertain docker with an endless loop
# Later we should trap signals and send them to init to control zabbix_server
while :
do
	echo "Press [CTRL+C] to stop.."
	sleep 1
done